### ISSUE TITLE
Not all `displayName`s are removed

### ISSUE THREAD

**Issue by svitovyda** [felixmosh/babel-plugin-transform-react-remove-display-name#1]
**Describe the bug**
Please see my little sandbox [project](https://github.com/svitovyda/udemy-react-swapi)
If you will run `yarn build:prod` without `transform-react-remove-display-name`, you will find 25 `"displayName"` in `output/main.js`. If you will enable it, there will still be 7 `"displayName"`, probably because those are the names of the components, wrapped into the `HOC`

**To Reproduce**
1. download https://github.com/svitovyda/udemy-react-swapi
2. build it, as described in README
3. run `yarn build:prod`
4. Open `output/main.js`
5. See 7 occurrences of setting the `displayName`

**Expected behavior**
0 `displayName` in the resulting production code

**Comment by felixmosh** [comment]
Hi @svitovyda, I'm glad that this lib is helpfull for you.
This lib was created for learning purpose & to solve a specific use-case, which it does.

I'm a bit busy lately, so it may take sometime.
If you have some time, will happy to review a PR that solves your use-cases.

**Comment by felixmosh** [comment]
HOC detection is added in `v1.1.0`
